language: go
sudo: false
go:
  - 1.10.x
  - 1.11.x
go_import_path: go.uber.org/zap
env:
  global:
    - TEST_TIMEOUT_SCALE=10
cache:
  directories:
    - vendor
install:
  - make dependencies

before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

script:
  - make lint
  - make test
  - make bench
  - fossa
after_success:
  - make cover
  - bash <(curl -s https://codecov.io/bash)
